### 🎯 Objective

Develop an industry-style feature mart for Probability of Default (PD) modeling by integrating applicant, bureau, previous credit history, and repayment behavior data into a unified customer-level analytical dataset.

The engineered feature set is designed to support scorecard development, WOE binning, variable selection, model training, and regulatory-style credit risk assessment.

---

### 📋 Feature Engineering Summary

| Category | Description |
|-----------|-------------|
| 👤 Applicant Profile | Demographics, employment stability, household characteristics and customer profile indicators |
| 💰 Financial Capacity | Income, credit burden, affordability and leverage ratios |
| 📊 External Risk Signals | External bureau scores, enquiry behaviour and social risk indicators |
| 🏦 Bureau Credit History | Tradelines, exposure, utilization, delinquency, vintage and product-level bureau performance |
| 📑 Previous Applications | Historical application behaviour, approval patterns and prior credit demand |
| 🔄 Repayment Behaviour | Delinquency patterns, DPD trends and installment repayment characteristics |
| 💳 Credit Product Behaviour | Product-level exposure, utilization and portfolio concentration measures |
| 🎯 Target Variable | Customer reaches 60+ DPD within a 12-month performance window |

In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [2]:

df = pd.read_csv("../Dataset/raw/application_train.csv")
df.shape

(307511, 122)

In [3]:
df.nunique()

SK_ID_CURR                    307511
TARGET                             2
NAME_CONTRACT_TYPE                 2
CODE_GENDER                        3
FLAG_OWN_CAR                       2
                               ...
AMT_REQ_CREDIT_BUREAU_DAY          9
AMT_REQ_CREDIT_BUREAU_WEEK         9
AMT_REQ_CREDIT_BUREAU_MON         24
AMT_REQ_CREDIT_BUREAU_QRT         11
AMT_REQ_CREDIT_BUREAU_YEAR        25
Length: 122, dtype: int64

In [4]:
df.head(2)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0000,0.0000,0.0252,0.0383,0.9722,0.6341,0.0144,0.0000,0.0690,0.0833,0.1250,0.0377,0.022,0.0198,0.0,0.0,0.0250,0.0369,0.9722,0.6243,0.0144,0.00,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0000,0.00,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
df_temp = df.copy()

In [6]:
application_df = pd.DataFrame(df['SK_ID_CURR'])
application_df.head(2)

   SK_ID_CURR
0      100002
1      100003

### Capacity Features

In [7]:
df_temp['credit_income_ratio'] = (
    df_temp['AMT_CREDIT'] /
    df_temp['AMT_INCOME_TOTAL']
)

df_temp['annuity_income_ratio'] = (
    df_temp['AMT_ANNUITY'] /
    df_temp['AMT_INCOME_TOTAL']
)

df_temp['goods_income_ratio'] = (
    df_temp['AMT_GOODS_PRICE'] /
    df_temp['AMT_INCOME_TOTAL']
)

df_temp['credit_goods_ratio'] = (
    df_temp['AMT_CREDIT'] /
    df_temp['AMT_GOODS_PRICE']
)

application_df = application_df.merge(
    df_temp[['SK_ID_CURR','credit_income_ratio','annuity_income_ratio','goods_income_ratio','credit_goods_ratio']], on = 'SK_ID_CURR', how = 'left'
)

application_df.shape

(307511, 5)

### Demographic Features

In [8]:
df_temp['age_years'] = abs(df_temp['DAYS_BIRTH']) / 365

df_temp['age_band'] = pd.cut(
    df_temp['age_years'],
    bins=[18,25,35,45,55,100]
)

df_temp = df_temp.rename(columns={'CNT_FAM_MEMBERS': 'count_family_members'})

df_temp['per_capita_income'] = (
    df_temp['AMT_INCOME_TOTAL'] /
    df_temp['count_family_members']
)


df_temp['children_ratio'] = (
    df_temp['CNT_CHILDREN'] /
    df_temp['count_family_members']
)

application_df = application_df.merge(
    df_temp[['SK_ID_CURR','age_years','count_family_members',
             'per_capita_income','children_ratio']], on = 'SK_ID_CURR', how = 'left'
)

application_df.shape

(307511, 9)

### Stability Features

In [9]:
df_temp['employment_years'] = (
    abs(df_temp['DAYS_EMPLOYED']) /
    365
)

df_temp['employment_age_ratio'] = (
    abs(df_temp['DAYS_EMPLOYED']) /
    abs(df_temp['DAYS_BIRTH'])
)

df_temp['registration_years'] = (
    abs(df_temp['DAYS_REGISTRATION']) /
    365
)

df_temp['id_publish_years'] = (
    abs(df_temp['DAYS_ID_PUBLISH']) /
    365
)

df_temp['owns_house'] = (
    df_temp['FLAG_OWN_REALTY'] == 'Y'
).astype(int)

df_temp['owns_car'] = (
    df_temp['FLAG_OWN_CAR'] == 'Y'
).astype(int)

df_temp = df_temp.rename(columns={'OWN_CAR_AGE': 'own_car_age'})


application_df = application_df.merge(
    df_temp[['SK_ID_CURR','employment_years','employment_age_ratio',
             'registration_years','id_publish_years','owns_house','owns_car','own_car_age']], on = 'SK_ID_CURR', how = 'left'
)

application_df.shape

(307511, 16)

### External Score Features

In [10]:
df_temp[['EXT_SOURCE_1','EXT_SOURCE_2','EXT_SOURCE_3']].describe()

        EXT_SOURCE_1  EXT_SOURCE_2   EXT_SOURCE_3
count  134133.000000  3.068510e+05  246546.000000
mean        0.502130  5.143927e-01       0.510853
std         0.211062  1.910602e-01       0.194844
min         0.014568  8.173617e-08       0.000527
25%         0.334007  3.924574e-01       0.370650
50%         0.505998  5.659614e-01       0.535276
75%         0.675053  6.636171e-01       0.669057
max         0.962693  8.549997e-01       0.896010

In [11]:
df_temp['ext_min'] = (
    df_temp[['EXT_SOURCE_1',
        'EXT_SOURCE_2',
        'EXT_SOURCE_3']]
    .min(axis=1)
)

df_temp['ext_mean'] = (
    df_temp[['EXT_SOURCE_1',
        'EXT_SOURCE_2',
        'EXT_SOURCE_3']]
    .mean(axis=1)
)

application_df = application_df.merge(
    df_temp[['SK_ID_CURR','ext_min','ext_mean']], on = 'SK_ID_CURR', how = 'left'
)

application_df.shape

(307511, 18)

### Conatctibility Features

In [12]:
contact_cols = [
'FLAG_MOBIL',
'FLAG_EMP_PHONE',
'FLAG_WORK_PHONE',
'FLAG_CONT_MOBILE',
'FLAG_PHONE',
'FLAG_EMAIL'
]

df_temp['contact_count'] = (
    df_temp[contact_cols]
    .sum(axis=1)
)

application_df = application_df.merge(
    df_temp[['SK_ID_CURR','contact_count']], on = 'SK_ID_CURR', how = 'left'
)

application_df.shape

(307511, 19)

### Document Verification

In [13]:
doc_cols = [
col for col in df_temp.columns
if 'FLAG_DOCUMENT' in col
]

df_temp['document_count'] = (
    df_temp[doc_cols]
    .sum(axis=1)
)

application_df = application_df.merge(
    df_temp[['SK_ID_CURR','document_count']], on = 'SK_ID_CURR', how = 'left'
)

application_df.shape

(307511, 20)

### Social Risk Features

In [14]:
df_temp['social_default_cnt'] = (
    df_temp['OBS_30_CNT_SOCIAL_CIRCLE']
    +
    df_temp['DEF_30_CNT_SOCIAL_CIRCLE']
)

df_temp['social_risk_ratio'] = (
    df_temp['DEF_30_CNT_SOCIAL_CIRCLE']
    /
    (df_temp['OBS_30_CNT_SOCIAL_CIRCLE']+1)
)

application_df = application_df.merge(
    df_temp[['SK_ID_CURR','social_default_cnt','social_risk_ratio']], on = 'SK_ID_CURR', how = 'left'
)

application_df.shape

(307511, 22)

### Enquiry Features

In [15]:
df_temp['no_enq_last_hour'] = df_temp['AMT_REQ_CREDIT_BUREAU_HOUR']

df_temp['no_enq_last_day'] = df_temp['AMT_REQ_CREDIT_BUREAU_DAY']

df_temp['no_enq_last_week'] = df_temp['AMT_REQ_CREDIT_BUREAU_WEEK']

df_temp['no_enq_last_month'] = df_temp['AMT_REQ_CREDIT_BUREAU_MON']

df_temp['no_enq_last_quarter'] = df_temp['AMT_REQ_CREDIT_BUREAU_QRT']

df_temp['no_enq_last_year'] = df_temp['AMT_REQ_CREDIT_BUREAU_YEAR']

df_temp['total_credit_enquiries'] = (
    df_temp['AMT_REQ_CREDIT_BUREAU_HOUR'].fillna(0)
    + df_temp['AMT_REQ_CREDIT_BUREAU_DAY'].fillna(0)
    + df_temp['AMT_REQ_CREDIT_BUREAU_WEEK'].fillna(0)
    + df_temp['AMT_REQ_CREDIT_BUREAU_MON'].fillna(0)
    + df_temp['AMT_REQ_CREDIT_BUREAU_QRT'].fillna(0)
    + df_temp['AMT_REQ_CREDIT_BUREAU_YEAR'].fillna(0)
)

df_temp['enquiry_L1M'] = (
    df_temp['AMT_REQ_CREDIT_BUREAU_DAY'].fillna(0)
    + df_temp['AMT_REQ_CREDIT_BUREAU_WEEK'].fillna(0)
    + df_temp['AMT_REQ_CREDIT_BUREAU_MON'].fillna(0)
)

df_temp['high_credit_hunger_flag'] = (
    df_temp['total_credit_enquiries'] >= 5
).astype(int)



application_df = application_df.merge(
    df_temp[['SK_ID_CURR','total_credit_enquiries','enquiry_L1M','high_credit_hunger_flag']], on = 'SK_ID_CURR', how = 'left'
)

application_df.shape

(307511, 25)

In [16]:
application_df.isnull().sum()

SK_ID_CURR                      0
credit_income_ratio             0
annuity_income_ratio           12
goods_income_ratio            278
credit_goods_ratio            278
age_years                       0
count_family_members            2
per_capita_income               2
children_ratio                  2
employment_years                0
employment_age_ratio            0
registration_years              0
id_publish_years                0
owns_house                      0
owns_car                        0
own_car_age                202929
ext_min                       172
ext_mean                      172
contact_count                   0
document_count                  0
social_default_cnt           1021
social_risk_ratio            1021
total_credit_enquiries          0
enquiry_L1M                     0
high_credit_hunger_flag         0
dtype: int64

### Bureau Features

In [17]:
bureau = pd.read_csv("../Dataset/raw/bureau.csv")
bureau.shape

(1716428, 17)

In [18]:
bureau.SK_ID_CURR.nunique(), bureau.SK_ID_BUREAU.nunique()

(305811, 1716428)

In [19]:
bureau.head(2)

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.0,0.0,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.0,171342.0,NaN,0.0,Credit card,-20,NaN

In [20]:
# 1. Create temporary flags for active and closed loans before grouping
bureau["is_active"] = (bureau["CREDIT_ACTIVE"] == "Active").astype(int)
bureau["is_closed"] = (bureau["CREDIT_ACTIVE"] == "Closed").astype(int)

# 2. Run a SINGLE unified aggregation step
bureau_features = (
    bureau.groupby("SK_ID_CURR")
    .agg(
        total_tradelines=("SK_ID_BUREAU", "count"),
        total_active_tradelines=("is_active", "sum"),
        total_closed_tradelines=("is_closed", "sum"),
        total_credit_exposure=("AMT_CREDIT_SUM", "sum"),
        total_debt=("AMT_CREDIT_SUM_DEBT", "sum"),
        total_overdue=("AMT_CREDIT_SUM_OVERDUE", "sum"),
        max_overdue=("AMT_CREDIT_SUM_OVERDUE", "max"),
        avg_credit_overdue_days=("CREDIT_DAY_OVERDUE", "mean"),
        max_credit_overdue_days=("CREDIT_DAY_OVERDUE", "max"),
        credit_prolongation_count=("CNT_CREDIT_PROLONG", "sum"),
        avg_days_credit=("DAYS_CREDIT", "mean"),
    )
    .reset_index()
)

# 3. Perform ratio calculations and flag assignments on the aggregated dataset
bureau_features["active_pct_tradelines"] = np.where(
    bureau_features["total_tradelines"] > 0,
    bureau_features["total_active_tradelines"]
    / bureau_features["total_tradelines"],
    0,
)

bureau_features["debt_to_utilization_ratio"] = np.where(
    bureau_features["total_credit_exposure"] > 0,
    bureau_features["total_debt"] / bureau_features["total_credit_exposure"],
    0,
)

bureau_features["avg_debt_per_tradeline"] = np.where(
    bureau_features["total_tradelines"] > 0,
    bureau_features["total_debt"] / bureau_features["total_tradelines"],
    0,
)

bureau_features["ever_delinquent_flag"] = (
    bureau_features["max_credit_overdue_days"] > 0
).astype(int)

bureau_features["avg_credit_age_years"] = (
    abs(bureau_features["avg_days_credit"]) / 365
)

# Drop the helper intermediate column used for age math
bureau_features.drop(columns=["avg_days_credit"], inplace=True)
bureau_features.shape

(305811, 16)

In [21]:
bureau.head(2)

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY,is_active,is_closed
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.0,0.0,NaN,0.0,Consumer credit,-131,NaN,0,1
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.0,171342.0,NaN,0.0,Credit card,-20,NaN,1,0

In [22]:
credit_type_map = {

    # Personal Loans
    'Consumer credit':'PL',
    'Cash loan (non-earmarked)':'PL',
    'Microloan':'PL',

    # Credit Cards
    'Credit card':'CC',

    # Home Loans
    'Mortgage':'HL',
    'Real estate loan':'HL',

    # Auto Loans
    'Car loan':'AL',

    # Business Loans
    'Loan for business development':'BL',
    'Loan for working capital replenishment':'BL',

    # Investment / Secured
    'Loan for purchase of shares (margin lending)':'INV',
    'Loan for the purchase of equipment':'INV',

    # Others
    'Another type of loan':'OTH',
    'Unknown type of loan':'OTH',
    'Mobile operator loan':'OTH',
    'Interbank credit':'OTH'
}

bureau['product_group'] = (
    bureau['CREDIT_TYPE']
    .map(credit_type_map)
)

bureau['tradeline_utilization'] = np.where(
    bureau['AMT_CREDIT_SUM'] > 0,
    bureau['AMT_CREDIT_SUM_DEBT'] /
    bureau['AMT_CREDIT_SUM'],
    np.nan
)

product_features = bureau.groupby(
    ['SK_ID_CURR','product_group']
).agg(

    num_accounts=('SK_ID_BUREAU','count'),

    total_exposure=('AMT_CREDIT_SUM','sum'),

    total_debt=('AMT_CREDIT_SUM_DEBT','sum'),

    total_overdue=('AMT_CREDIT_SUM_OVERDUE','sum'),

    avg_utilization=('tradeline_utilization','mean')

).reset_index()

product_features['utilization'] = np.where(
    product_features['total_exposure'] > 0,
    product_features['total_debt'] /
    product_features['total_exposure'],
    np.nan
)

bureau_prod = product_features.pivot(
    index='SK_ID_CURR',
    columns='product_group',
    values=[
        'num_accounts',
        'total_exposure',
        'total_debt',
        'total_overdue',
        'utilization'
    ]
)

bureau_prod.columns = [

    f"{metric}_{prod}"

    for metric, prod

    in bureau_prod.columns

]

bureau_prod = bureau_prod.reset_index()


active_accounts = (

    bureau[
        bureau['CREDIT_ACTIVE']=='Active'
    ]

    .groupby(
        ['SK_ID_CURR','product_group']
    )

    .size()

    .unstack(fill_value=0)

)

active_accounts.columns = [

    f'active_{col.lower()}'

    for col

    in active_accounts.columns

]

active_accounts = active_accounts.reset_index()


bureau_prod = bureau_prod.merge(

    active_accounts,

    on='SK_ID_CURR',

    how='left'

)

bureau_prod = bureau_prod.fillna(0)

bureau_prod.shape

(305811, 43)

In [23]:
bureau_features = bureau_features.merge(bureau_prod, on='SK_ID_CURR', how='left')
bureau_features.shape

(305811, 58)

In [24]:
bureau_balance = pd.read_csv("../Dataset/raw/bureau_balance.csv")
bureau_balance.shape

(27299925, 3)

In [25]:
bureau_balance.SK_ID_BUREAU.nunique()

817395

In [27]:
bureau_balance.head(2)

   SK_ID_BUREAU  MONTHS_BALANCE STATUS
0       5715448               0      C
1       5715448              -1      C

In [28]:
bureau_balance.MONTHS_BALANCE.value_counts()

MONTHS_BALANCE
-1     622601
-2     619243
-3     615080
 0     610965
-4     609138
        ...
-92     57300
-93     53535
-94     49965
-95     46542
-96     43147
Name: count, Length: 97, dtype: int64

In [29]:
bureau_balance.STATUS.value_counts()

STATUS
C    13646993
0     7499507
X     5810482
1      242347
5       62406
2       23419
3        8924
4        5847
Name: count, dtype: int64

In [30]:
# 1. Map status quickly using a vectorized map
status_map = {
    "X": -999,
    "C": 0,
    "0": 0,
    "1": 30,
    "2": 60,
    "3": 90,
    "4": 120,
    "5": 150,
}
bureau_balance["dpd"] = bureau_balance["STATUS"].map(status_map)

# 2. Vectorize the condition check flags BEFORE grouping (No lambdas!)
bureau_balance["is_30"] = (bureau_balance["dpd"] >= 30).astype(int)
bureau_balance["is_60"] = (bureau_balance["dpd"] >= 60).astype(int)
bureau_balance["is_90"] = (bureau_balance["dpd"] >= 90).astype(int)
bureau_balance["is_120"] = (bureau_balance["dpd"] >= 120).astype(int)
bureau_balance["is_150"] = (bureau_balance["dpd"] >= 150).astype(int)

# 3. Create time-window masks using numpy where
for m in [1, 3, 6, 12]:
    mask = bureau_balance["MONTHS_BALANCE"] >= -m
    bureau_balance[f"dpd_l{m}m"] = np.where(mask, bureau_balance["dpd"], np.nan)
    bureau_balance[f"is_30_l{m}m"] = np.where(mask, bureau_balance["is_30"], 0)
    bureau_balance[f"is_60_l{m}m"] = np.where(mask, bureau_balance["is_60"], 0)
    bureau_balance[f"is_90_l{m}m"] = np.where(mask, bureau_balance["is_90"], 0)
    bureau_balance[f"is_120_l{m}m"] = np.where(mask, bureau_balance["is_120"], 0)
    bureau_balance[f"is_150_l{m}m"] = np.where(mask, bureau_balance["is_150"], 0)

# 4. Execute a SINGLE unified group operation with optimized Cython aggregations ('max' and 'sum')
dpd_features = (
    bureau_balance.groupby("SK_ID_BUREAU")
    .agg(
        # 1 Month Window
        max_dpd_l1m=("dpd_l1m", "max"),
        cnt_30dpd_l1m=("is_30_l1m", "sum"),
        cnt_60dpd_l1m=("is_60_l1m", "sum"),
        cnt_90dpd_l1m=("is_90_l1m", "sum"),
        cnt_120dpd_l1m=("is_120_l1m", "sum"),
        cnt_150dpd_l1m=("is_150_l1m", "sum"),
        # 3 Month Window
        max_dpd_l3m=("dpd_l3m", "max"),
        cnt_30dpd_l3m=("is_30_l3m", "sum"),
        cnt_60dpd_l3m=("is_60_l3m", "sum"),
        cnt_90dpd_l3m=("is_90_l3m", "sum"),
        cnt_120dpd_l3m=("is_120_l3m", "sum"),
        cnt_150dpd_l3m=("is_150_l3m", "sum"),
        # 6 Month Window
        max_dpd_l6m=("dpd_l6m", "max"),
        cnt_30dpd_l6m=("is_30_l6m", "sum"),
        cnt_60dpd_l6m=("is_60_l6m", "sum"),
        cnt_90dpd_l6m=("is_90_l6m", "sum"),
        cnt_120dpd_l6m=("is_120_l6m", "sum"),
        cnt_150dpd_l6m=("is_150_l6m", "sum"),
        # 12 Month Window
        max_dpd_l12m=("dpd_l12m", "max"),
        cnt_30dpd_l12m=("is_30_l12m", "sum"),
        cnt_60dpd_l12m=("is_60_l12m", "sum"),
        cnt_90dpd_l12m=("is_90_l12m", "sum"),
        cnt_120dpd_l12m=("is_120_l12m", "sum"),
        cnt_150dpd_l12m=("is_150_l12m", "sum"),
    )
    .reset_index()
)

# Optional clean up: drop temporary columns added to bureau_balance to free RAM
drop_cols = [c for c in bureau_balance.columns if "is_" in c or "m" in c]
bureau_balance.drop(columns=drop_cols, inplace=True, errors="ignore")

In [31]:
dpd_features.shape

(817395, 25)

In [32]:
dpd_features.head(2)

,SK_ID_BUREAU,max_dpd_l1m,cnt_30dpd_l1m,cnt_60dpd_l1m,cnt_90dpd_l1m,cnt_120dpd_l1m,cnt_150dpd_l1m,max_dpd_l3m,cnt_30dpd_l3m,cnt_60dpd_l3m,cnt_90dpd_l3m,cnt_120dpd_l3m,cnt_150dpd_l3m,max_dpd_l6m,cnt_30dpd_l6m,cnt_60dpd_l6m,cnt_90dpd_l6m,cnt_120dpd_l6m,cnt_150dpd_l6m,max_dpd_l12m,cnt_30dpd_l12m,cnt_60dpd_l12m,cnt_90dpd_l12m,cnt_120dpd_l12m,cnt_150dpd_l12m
0,5001709,0.0,0,0,0,0,0,0.0,0,0,0,0,0,0.0,0,0,0,0,0,0.0,0,0,0,0,0
1,5001710,0.0,0,0,0,0,0,0.0,0,0,0,0,0,0.0,0,0,0,0,0,0.0,0,0,0,0,0

In [33]:
bureau_enriched = bureau.merge(
    dpd_features,
    on='SK_ID_BUREAU',
    how='left'
)

bureau_enriched.shape

(1716428, 45)

In [34]:
windows = ['l1m', 'l3m', 'l6m', 'l12m']

agg_dict = {}

# Maximum DPD
for w in windows:
    agg_dict[f'max_dpd_{w}'] = (f'max_dpd_{w}', 'max')

# Count DPDs
for w in windows:
    for dpd in [30, 60, 90]:
        agg_dict[f'total_{dpd}dpd_{w}'] = (
            f'cnt_{dpd}dpd_{w}',
            'sum'
        )

customer_dpd = (
    bureau_enriched
    .groupby('SK_ID_CURR')
    .agg(**agg_dict)
    .reset_index()
)

customer_dpd.shape

(305811, 17)

In [35]:
major_products = (
    bureau_enriched['product_group']
    .dropna()
    .unique()
    .tolist()
)

windows = ['l1m', 'l3m', 'l6m', 'l12m']

prod_frames = []

for prod in major_products:

    agg_dict = {}

    # Max DPD Features
    for w in windows:
        agg_dict[f'max_dpd_{w}'] = (
            f'max_dpd_{w}',
            'max'
        )

    # Count DPD Features
    for w in windows:
        for dpd in [30, 60, 90]:
            agg_dict[f'cnt_{dpd}dpd_{w}'] = (
                f'cnt_{dpd}dpd_{w}',
                'sum'
            )

    temp = (
        bureau_enriched[
            bureau_enriched['product_group'] == prod
        ]
        .groupby('SK_ID_CURR')
        .agg(**agg_dict)
        .add_prefix(f'{prod}_')
        .reset_index()
    )

    prod_frames.append(temp)

# Combine all product-level feature tables
product_dpd_features = prod_frames[0]

for df_temp in prod_frames[1:]:
    product_dpd_features = product_dpd_features.merge(
        df_temp,
        on='SK_ID_CURR',
        how='outer'
    )

product_dpd_features = product_dpd_features.fillna(0)

# Merge with existing bureau features
bureau_features_final = (
    bureau_features
    .merge(
        product_dpd_features,
        on='SK_ID_CURR',
        how='left'
    ).merge(
        customer_dpd,
        on='SK_ID_CURR',
        how='left'
    )
    .fillna(0)
)

print("Final Bureau Features Shape :", bureau_features_final.shape)

bureau_features_final.head(2)

Final Bureau Features Shape : (305811, 186)

,SK_ID_CURR,total_tradelines,total_active_tradelines,total_closed_tradelines,total_credit_exposure,total_debt,total_overdue,max_overdue,avg_credit_overdue_days,max_credit_overdue_days,credit_prolongation_count,active_pct_tradelines,debt_to_utilization_ratio,avg_debt_per_tradeline,ever_delinquent_flag,avg_credit_age_years,num_accounts_AL,num_accounts_BL,num_accounts_CC,num_accounts_HL,num_accounts_INV,num_accounts_OTH,num_accounts_PL,total_exposure_AL,total_exposure_BL,total_exposure_CC,total_exposure_HL,total_exposure_INV,total_exposure_OTH,total_exposure_PL,total_debt_AL,total_debt_BL,total_debt_CC,total_debt_HL,total_debt_INV,total_debt_OTH,total_debt_PL,total_overdue_AL,total_overdue_BL,total_overdue_CC,total_overdue_HL,total_overdue_INV,total_overdue_OTH,total_overdue_PL,utilization_AL,utilization_BL,utilization_CC,utilization_HL,utilization_INV,utilization_OTH,utilization_PL,active_al,active_bl,active_cc,active_hl,active_inv,active_oth,active_pl,PL_max_dpd_l1m,PL_max_dpd_l3m,PL_max_dpd_l6m,PL_max_dpd_l12m,PL_cnt_30dpd_l1m,PL_cnt_60dpd_l1m,PL_cnt_90dpd_l1m,PL_cnt_30dpd_l3m,PL_cnt_60dpd_l3m,PL_cnt_90dpd_l3m,PL_cnt_30dpd_l6m,PL_cnt_60dpd_l6m,PL_cnt_90dpd_l6m,PL_cnt_30dpd_l12m,PL_cnt_60dpd_l12m,PL_cnt_90dpd_l12m,CC_max_dpd_l1m,CC_max_dpd_l3m,CC_max_dpd_l6m,CC_max_dpd_l12m,CC_cnt_30dpd_l1m,CC_cnt_60dpd_l1m,CC_cnt_90dpd_l1m,CC_cnt_30dpd_l3m,CC_cnt_60dpd_l3m,CC_cnt_90dpd_l3m,CC_cnt_30dpd_l6m,CC_cnt_60dpd_l6m,CC_cnt_90dpd_l6m,CC_cnt_30dpd_l12m,CC_cnt_60dpd_l12m,CC_cnt_90dpd_l12m,HL_max_dpd_l1m,HL_max_dpd_l3m,HL_max_dpd_l6m,HL_max_dpd_l12m,HL_cnt_30dpd_l1m,HL_cnt_60dpd_l1m,HL_cnt_90dpd_l1m,HL_cnt_30dpd_l3m,HL_cnt_60dpd_l3m,HL_cnt_90dpd_l3m,HL_cnt_30dpd_l6m,HL_cnt_60dpd_l6m,HL_cnt_90dpd_l6m,HL_cnt_30dpd_l12m,HL_cnt_60dpd_l12m,HL_cnt_90dpd_l12m,AL_max_dpd_l1m,AL_max_dpd_l3m,AL_max_dpd_l6m,AL_max_dpd_l12m,AL_cnt_30dpd_l1m,AL_cnt_60dpd_l1m,AL_cnt_90dpd_l1m,AL_cnt_30dpd_l3m,AL_cnt_60dpd_l3m,AL_cnt_90dpd_l3m,AL_cnt_30dpd_l6m,AL_cnt_60dpd_l6m,AL_cnt_90dpd_l6m,AL_cnt_30dpd_l12m,AL_cnt_60dpd_l12m,AL_cnt_90dpd_l12m,BL_max_dpd_l1m,BL_max_dpd_l3m,BL_max_dpd_l6m,BL_max_dpd_l12m,BL_cnt_30dpd_l1m,BL_cnt_60dpd_l1m,BL_cnt_90dpd_l1m,BL_cnt_30dpd_l3m,BL_cnt_60dpd_l3m,BL_cnt_90dpd_l3m,BL_cnt_30dpd_l6m,BL_cnt_60dpd_l6m,BL_cnt_90dpd_l6m,BL_cnt_30dpd_l12m,BL_cnt_60dpd_l12m,BL_cnt_90dpd_l12m,OTH_max_dpd_l1m,OTH_max_dpd_l3m,OTH_max_dpd_l6m,OTH_max_dpd_l12m,OTH_cnt_30dpd_l1m,OTH_cnt_60dpd_l1m,OTH_cnt_90dpd_l1m,OTH_cnt_30dpd_l3m,OTH_cnt_60dpd_l3m,OTH_cnt_90dpd_l3m,OTH_cnt_30dpd_l6m,OTH_cnt_60dpd_l6m,OTH_cnt_90dpd_l6m,OTH_cnt_30dpd_l12m,OTH_cnt_60dpd_l12m,OTH_cnt_90dpd_l12m,INV_max_dpd_l1m,INV_max_dpd_l3m,INV_max_dpd_l6m,INV_max_dpd_l12m,INV_cnt_30dpd_l1m,INV_cnt_60dpd_l1m,INV_cnt_90dpd_l1m,INV_cnt_30dpd_l3m,INV_cnt_60dpd_l3m,INV_cnt_90dpd_l3m,INV_cnt_30dpd_l6m,INV_cnt_60dpd_l6m,INV_cnt_90dpd_l6m,INV_cnt_30dpd_l12m,INV_cnt_60dpd_l12m,INV_cnt_90dpd_l12m,max_dpd_l1m,max_dpd_l3m,max_dpd_l6m,max_dpd_l12m,total_30dpd_l1m,total_60dpd_l1m,total_90dpd_l1m,total_30dpd_l3m,total_60dpd_l3m,total_90dpd_l3m,total_30dpd_l6m,total_60dpd_l6m,total_90dpd_l6m,total_30dpd_l12m,total_60dpd_l12m,total_90dpd_l12m
0,100001,7,3,4,1453365.000,596686.5,0.0,0.0,0.0,0,0,0.428571,0.410555,85240.928571,0,2.013699,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.000,0.0,0.0,0.0,1453365.0,0.0,0.0,0.0,0.0,0.0,0.0,596686.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.410555,0.0,0.0,0.0,0.0,0.0,0.0,3.0,30.0,30.0,30.0,30.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,30.0,30.0,30.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1,100002,8,2,6,865055.565,245781.0,0.0,0.0,0.0,0,0,0.250000,0.284122,30722.625000,0,2.394521,0.0,0.0,4.0,0.0,0.0,0.0,4.0,0.0,0.0,140249.565,0.0,0.0,0.0,724806.0,0.0,0.0,0.0,0.0,0.0,0.0,245781.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.339099,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Previous Application, POS_CASH Balance related Featues

In [36]:
prev = pd.read_csv("../Dataset/raw/previous_application.csv")
prev.shape

(1670214, 37)

In [37]:
prev.SK_ID_CURR.nunique(), prev.SK_ID_PREV.nunique()

(338857, 1670214)

In [38]:
prev.head(2)

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,RATE_DOWN_PAYMENT,RATE_INTEREST_PRIMARY,RATE_INTEREST_PRIVILEGED,NAME_CASH_LOAN_PURPOSE,NAME_CONTRACT_STATUS,DAYS_DECISION,NAME_PAYMENT_TYPE,CODE_REJECT_REASON,NAME_TYPE_SUITE,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,Y,1,0.0,0.182832,0.867336,XAP,Approved,-73,Cash through the bank,XAP,NaN,Repeater,Mobile,POS,XNA,Country-wide,35,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,Y,1,NaN,NaN,NaN,XNA,Approved,-164,XNA,XAP,Unaccompanied,Repeater,XNA,Cash,x-sell,Contact center,-1,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0

In [39]:
a = prev.SK_ID_CURR.unique().tolist()
b = prev.SK_ID_PREV.unique().tolist()

c = set(a).intersection(set(b))
len(c)

0

In [40]:
prev_feat = prev.groupby(
    'SK_ID_CURR'
).agg(
    num_prev_apps=('SK_ID_PREV','count')
)

prev['is_approved'] = (
    prev['NAME_CONTRACT_STATUS']
    == 'Approved'
).astype(int)

prev['is_refused'] = (
    prev['NAME_CONTRACT_STATUS']
    == 'Refused'
).astype(int)

prev['is_cancelled'] = (
    prev['NAME_CONTRACT_STATUS']
    == 'Canceled'
).astype(int)

approval_features = prev.groupby(
    'SK_ID_CURR'
).agg(
    num_approved=('is_approved','sum'),
    num_refused=('is_refused','sum'),
    num_cancelled=('is_cancelled','sum')
)

approval_features['approval_rate'] = (
    approval_features['num_approved']
    /
    approval_features.sum(axis=1)
)

approval_features['rejection_rate'] = (
    approval_features['num_refused']
    /
    approval_features.sum(axis=1)
)

amount_features = prev.groupby(
    'SK_ID_CURR'
).agg(
    avg_application_amt=('AMT_APPLICATION','mean'),
    max_application_amt=('AMT_APPLICATION','max'),

    avg_credit_amt=('AMT_CREDIT','mean'),
    max_credit_amt=('AMT_CREDIT','max')
)

prev['credit_grant_ratio'] = (
    prev['AMT_CREDIT']
    /
    prev['AMT_APPLICATION']
)

grant_features = prev.groupby(
    'SK_ID_CURR'
).agg(
    avg_credit_grant_ratio=(
        'credit_grant_ratio',
        'mean'
    ),
    min_credit_grant_ratio=(
        'credit_grant_ratio',
        'min'
    )
)

term_features = prev.groupby(
    'SK_ID_CURR'
).agg(
    avg_prev_term=('CNT_PAYMENT','mean'),
    max_prev_term=('CNT_PAYMENT','max')
)

time_features = prev.groupby(
    'SK_ID_CURR'
).agg(
    days_since_last_application=(
        'DAYS_DECISION',
        'max'
    )
)


insurance_features = prev.groupby(
    'SK_ID_CURR'
).agg(
    insurance_rate=(
        'NFLAG_INSURED_ON_APPROVAL',
        'mean'
    )
)

from functools import reduce

prev_feature_list = [

    prev_feat,
    approval_features,
    amount_features,
    grant_features,
    term_features,
    time_features,
    insurance_features

]

previous_application_features = reduce(
    lambda left,right:
    left.merge(
        right,
        left_index=True,
        right_index=True,
        how='outer'
    ),
    prev_feature_list
).reset_index()

previous_application_features.shape

(338857, 17)

In [41]:
previous_application_features = previous_application_features.fillna(-999)
previous_application_features.head(2)

,SK_ID_CURR,num_prev_apps,num_approved,num_refused,num_cancelled,approval_rate,rejection_rate,avg_application_amt,max_application_amt,avg_credit_amt,max_credit_amt,avg_credit_grant_ratio,min_credit_grant_ratio,avg_prev_term,max_prev_term,days_since_last_application,insurance_rate
0,100001,1,1,0,0,1.0,0.0,24835.5,24835.5,23787.0,23787.0,0.957782,0.957782,8.0,8.0,-1740,0.0
1,100002,1,1,0,0,1.0,0.0,179055.0,179055.0,179055.0,179055.0,1.000000,1.000000,24.0,24.0,-606,0.0

In [42]:
# POS CASH BALANCE Data

on_us = pd.read_csv("../Dataset/raw/POS_CASH_balance.csv")
on_us.shape

(10001358, 8)

In [43]:
on_us.head(2)

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,1803195,182943,-31,48.0,45.0,Active,0,0
1,1715348,367990,-33,36.0,35.0,Active,0,0

In [44]:
on_us.SK_ID_CURR.nunique(), on_us.SK_ID_PREV.nunique()

(337252, 936325)

In [45]:
on_us_dpd = on_us.groupby(
    'SK_ID_CURR'
).agg(
    on_us_max_dpd=('SK_DPD','max'),
    on_us_avg_dpd=('SK_DPD','mean')
)

on_us['dpd30'] = (
    on_us['SK_DPD'] >= 30
).astype(int)

on_us['dpd60'] = (
    on_us['SK_DPD'] >= 60
).astype(int)

on_us['dpd90'] = (
    on_us['SK_DPD'] >= 90
).astype(int)

on_us_count = on_us.groupby(
    'SK_ID_CURR'
).agg(
    on_us_cnt_30dpd=('dpd30','sum'),
    on_us_cnt_60dpd=('dpd60','sum'),
    on_us_cnt_90dpd=('dpd90','sum')
)

remaining_features = on_us.groupby(
    'SK_ID_CURR'
).agg(
    avg_instalment_remaining=(
        'CNT_INSTALMENT_FUTURE',
        'mean'
    )
)

on_us_features = (
    on_us_dpd
    .merge(
        on_us_count,
        left_index=True,
        right_index=True
    )
    .merge(
        remaining_features,
        left_index=True,
        right_index=True
    )
    .reset_index()
)

on_us_features.shape

(337252, 7)

In [46]:
on_us_features.head(2)

,SK_ID_CURR,on_us_max_dpd,on_us_avg_dpd,on_us_cnt_30dpd,on_us_cnt_60dpd,on_us_cnt_90dpd,avg_instalment_remaining
0,100001,7,0.777778,0,0,0,1.444444
1,100002,0,0.000000,0,0,0,15.000000

In [47]:
on_us_features = on_us_features.fillna(-999)

In [48]:
on_us_features.shape, previous_application_features.shape, bureau_features_final.shape, application_df.shape

((337252, 7), (338857, 17), (305811, 186), (307511, 25))

### Target Creation : 60+ DPD in 12M Performance Window

In [49]:
# Define the path to your file
file_path = "../Dataset/raw/installments_payments.csv"

# Columns we actually need to build the target
use_cols = ['SK_ID_CURR', 'DAYS_INSTALMENT', 'DAYS_ENTRY_PAYMENT']

# Dictionary to hold aggregated results from each chunk
chunk_targets = []

# Define chunk size (1 million rows at a time uses very little RAM)
chunk_size = 1_000_000

print("Processing installments_payments.csv in chunks...")

for chunk in pd.read_csv(file_path, usecols=use_cols, chunksize=chunk_size):
    # 1. Filter immediately for the 12-month Performance Window
    # (DAYS_INSTALMENT between -365 and 0)
    chunk_filtered = chunk[(chunk['DAYS_INSTALMENT'] >= -365) & (chunk['DAYS_INSTALMENT'] <= 0)].copy()
    
    if chunk_filtered.empty:
        continue
        
    # 2. Calculate DPD (Clip at lower bound 0)
    chunk_filtered['DPD'] = chunk_filtered['DAYS_ENTRY_PAYMENT'] - chunk_filtered['DAYS_INSTALMENT']
    chunk_filtered['DPD'] = chunk_filtered['DPD'].clip(lower=0)
    
    # 3. Create the 60+ DPD Flag
    chunk_filtered['bad_60_flag'] = (chunk_filtered['DPD'] >= 60).astype(int)
    
    # 4. Preliminary aggregation at chunk level to save space
    chunk_agg = chunk_filtered.groupby('SK_ID_CURR')['bad_60_flag'].max().reset_index()
    
    chunk_targets.append(chunk_agg)

print("Chunks processed. Combining and performing final aggregation...")

# 5. Concatenate all chunk results
combined_df = pd.concat(chunk_targets, ignore_index=True)

# 6. Final aggregation (in case a customer appeared across different chunks)
target_df = combined_df.groupby('SK_ID_CURR').agg(TARGET=('bad_60_flag', 'max')).reset_index()

print(f"Target dataframe created successfully! Shape: {target_df.shape}")
print(f"Bad Rate: {target_df['TARGET'].mean() * 100:.2f}%")

Processing installments_payments.csv in chunks...
Chunks processed. Combining and performing final aggregation...
Target dataframe created successfully! Shape: (252761, 2)
Bad Rate: 0.18%

In [50]:
target_df.TARGET.value_counts(normalize=True)

TARGET
0    0.998247
1    0.001753
Name: proportion, dtype: float64

### Target Definition (Revisited)

Roll-rate analysis identified 60+ DPD as a meaningful deterioration threshold with significant migration into severe delinquency buckets.

Vintage analysis was performed to evaluate portfolio performance stability and support the conceptual selection of a 12-month performance horizon.

Due to limitations in reconstructing a precise account-level forward-looking performance window from the publicly available Home Credit dataset, the final modeling target was defined as:

**TARGET = 1**
- Customer experienced at least one 60+ DPD event in observed repayment history.

**TARGET = 0**
- Customer never experienced a 60+ DPD event.

The resulting bad rate of approximately 2.9% is consistent with severe delinquency-based Probability of Default (PD) modeling.

In [52]:
inst = pd.read_csv(
    "../Dataset/raw/installments_payments.csv",
    usecols=[
        'SK_ID_CURR',
        'DAYS_INSTALMENT',
        'DAYS_ENTRY_PAYMENT'
    ]
)

inst['DPD'] = (
    inst['DAYS_ENTRY_PAYMENT']
    - inst['DAYS_INSTALMENT']
).clip(lower=0)

inst['bad60'] = (
    inst['DPD'] >= 60
).astype(int)

target_all = (
    inst.groupby('SK_ID_CURR')
    ['bad60']
    .max()
)

print("Ever 60+ DPD Bad Rate:")
print(target_all.mean())

print("Total Customers:")
print(target_all.shape[0])

print("Total Bads:")
print(target_all.sum())

Ever 60+ DPD Bad Rate:
0.029126556670308345
Total Customers:
339587
Total Bads:
9891

In [53]:
inst['DPD'] = (
    inst['DAYS_ENTRY_PAYMENT']
    - inst['DAYS_INSTALMENT']
).clip(lower=0)

inst['bad60'] = (
    inst['DPD'] >= 60
).astype(int)

target_df = (
    inst.groupby('SK_ID_CURR')
    ['bad60']
    .max()
    .reset_index()
    .rename(columns={'bad60':'TARGET'})
)

In [54]:
target_df.TARGET.value_counts(normalize=True)

TARGET
0    0.970873
1    0.029127
Name: proportion, dtype: float64

In [55]:
master_df = (
    application_df
    .merge(bureau_features_final,on='SK_ID_CURR',how='left')
    .merge(previous_application_features,on='SK_ID_CURR',how='left')
    .merge(on_us_features,on='SK_ID_CURR',how='left')
    .merge(target_df,on='SK_ID_CURR',how='inner')
)

master_df.shape, master_df.isnull().sum()

((291643, 233),
 SK_ID_CURR                     0
 credit_income_ratio            0
 annuity_income_ratio          12
 goods_income_ratio           267
 credit_goods_ratio           267
                             ...
 on_us_cnt_30dpd             2632
 on_us_cnt_60dpd             2632
 on_us_cnt_90dpd             2632
 avg_instalment_remaining    2632
 TARGET                         0
 Length: 233, dtype: int64)

In [56]:
master_df.head(2)

,SK_ID_CURR,credit_income_ratio,annuity_income_ratio,goods_income_ratio,credit_goods_ratio,age_years,count_family_members,per_capita_income,children_ratio,employment_years,employment_age_ratio,registration_years,id_publish_years,owns_house,owns_car,own_car_age,ext_min,ext_mean,contact_count,document_count,social_default_cnt,social_risk_ratio,total_credit_enquiries,enquiry_L1M,high_credit_hunger_flag,total_tradelines,total_active_tradelines,total_closed_tradelines,total_credit_exposure,total_debt,total_overdue,max_overdue,avg_credit_overdue_days,max_credit_overdue_days,credit_prolongation_count,active_pct_tradelines,debt_to_utilization_ratio,avg_debt_per_tradeline,ever_delinquent_flag,avg_credit_age_years,num_accounts_AL,num_accounts_BL,num_accounts_CC,num_accounts_HL,num_accounts_INV,num_accounts_OTH,num_accounts_PL,total_exposure_AL,total_exposure_BL,total_exposure_CC,total_exposure_HL,total_exposure_INV,total_exposure_OTH,total_exposure_PL,total_debt_AL,total_debt_BL,total_debt_CC,total_debt_HL,total_debt_INV,total_debt_OTH,total_debt_PL,total_overdue_AL,total_overdue_BL,total_overdue_CC,total_overdue_HL,total_overdue_INV,total_overdue_OTH,total_overdue_PL,utilization_AL,utilization_BL,utilization_CC,utilization_HL,utilization_INV,utilization_OTH,utilization_PL,active_al,active_bl,active_cc,active_hl,active_inv,active_oth,active_pl,PL_max_dpd_l1m,PL_max_dpd_l3m,PL_max_dpd_l6m,PL_max_dpd_l12m,PL_cnt_30dpd_l1m,PL_cnt_60dpd_l1m,PL_cnt_90dpd_l1m,PL_cnt_30dpd_l3m,PL_cnt_60dpd_l3m,PL_cnt_90dpd_l3m,PL_cnt_30dpd_l6m,PL_cnt_60dpd_l6m,PL_cnt_90dpd_l6m,PL_cnt_30dpd_l12m,PL_cnt_60dpd_l12m,PL_cnt_90dpd_l12m,CC_max_dpd_l1m,CC_max_dpd_l3m,CC_max_dpd_l6m,CC_max_dpd_l12m,CC_cnt_30dpd_l1m,CC_cnt_60dpd_l1m,CC_cnt_90dpd_l1m,CC_cnt_30dpd_l3m,CC_cnt_60dpd_l3m,CC_cnt_90dpd_l3m,CC_cnt_30dpd_l6m,CC_cnt_60dpd_l6m,CC_cnt_90dpd_l6m,CC_cnt_30dpd_l12m,CC_cnt_60dpd_l12m,CC_cnt_90dpd_l12m,HL_max_dpd_l1m,HL_max_dpd_l3m,HL_max_dpd_l6m,HL_max_dpd_l12m,HL_cnt_30dpd_l1m,HL_cnt_60dpd_l1m,HL_cnt_90dpd_l1m,HL_cnt_30dpd_l3m,HL_cnt_60dpd_l3m,HL_cnt_90dpd_l3m,HL_cnt_30dpd_l6m,HL_cnt_60dpd_l6m,HL_cnt_90dpd_l6m,HL_cnt_30dpd_l12m,HL_cnt_60dpd_l12m,HL_cnt_90dpd_l12m,AL_max_dpd_l1m,AL_max_dpd_l3m,AL_max_dpd_l6m,AL_max_dpd_l12m,AL_cnt_30dpd_l1m,AL_cnt_60dpd_l1m,AL_cnt_90dpd_l1m,AL_cnt_30dpd_l3m,AL_cnt_60dpd_l3m,AL_cnt_90dpd_l3m,AL_cnt_30dpd_l6m,AL_cnt_60dpd_l6m,AL_cnt_90dpd_l6m,AL_cnt_30dpd_l12m,AL_cnt_60dpd_l12m,AL_cnt_90dpd_l12m,BL_max_dpd_l1m,BL_max_dpd_l3m,BL_max_dpd_l6m,BL_max_dpd_l12m,BL_cnt_30dpd_l1m,BL_cnt_60dpd_l1m,BL_cnt_90dpd_l1m,BL_cnt_30dpd_l3m,BL_cnt_60dpd_l3m,BL_cnt_90dpd_l3m,BL_cnt_30dpd_l6m,BL_cnt_60dpd_l6m,BL_cnt_90dpd_l6m,BL_cnt_30dpd_l12m,BL_cnt_60dpd_l12m,BL_cnt_90dpd_l12m,OTH_max_dpd_l1m,OTH_max_dpd_l3m,OTH_max_dpd_l6m,OTH_max_dpd_l12m,OTH_cnt_30dpd_l1m,OTH_cnt_60dpd_l1m,OTH_cnt_90dpd_l1m,OTH_cnt_30dpd_l3m,OTH_cnt_60dpd_l3m,OTH_cnt_90dpd_l3m,OTH_cnt_30dpd_l6m,OTH_cnt_60dpd_l6m,OTH_cnt_90dpd_l6m,OTH_cnt_30dpd_l12m,OTH_cnt_60dpd_l12m,OTH_cnt_90dpd_l12m,INV_max_dpd_l1m,INV_max_dpd_l3m,INV_max_dpd_l6m,INV_max_dpd_l12m,INV_cnt_30dpd_l1m,INV_cnt_60dpd_l1m,INV_cnt_90dpd_l1m,INV_cnt_30dpd_l3m,INV_cnt_60dpd_l3m,INV_cnt_90dpd_l3m,INV_cnt_30dpd_l6m,INV_cnt_60dpd_l6m,INV_cnt_90dpd_l6m,INV_cnt_30dpd_l12m,INV_cnt_60dpd_l12m,INV_cnt_90dpd_l12m,max_dpd_l1m,max_dpd_l3m,max_dpd_l6m,max_dpd_l12m,total_30dpd_l1m,total_60dpd_l1m,total_90dpd_l1m,total_30dpd_l3m,total_60dpd_l3m,total_90dpd_l3m,total_30dpd_l6m,total_60dpd_l6m,total_90dpd_l6m,total_30dpd_l12m,total_60dpd_l12m,total_90dpd_l12m,num_prev_apps,num_approved,num_refused,num_cancelled,approval_rate,rejection_rate,avg_application_amt,max_application_amt,avg_credit_amt,max_credit_amt,avg_credit_grant_ratio,min_credit_grant_ratio,avg_prev_term,max_prev_term,days_since_last_application,insurance_rate,on_us_max_dpd,on_us_avg_dpd,on_us_cnt_30dpd,on_us_cnt_60dpd,on_us_cnt_90dpd,avg_instalment_remaining,TARGET
0,100002,2.007889,0.121978,1.733333,1.158397,25.920548,1.0,202500.0,0.0,1.745205,0.067329,9.994521,5.808219,1,0,NaN,0.083037,0.161787,4,1,4.0,0.666667,1.0,0.0,0,8.0,2.0,6.0,865055.565,245781.0,0.0,0.0,0.0,0.0,0.0,0.25,0.284122,30722.625,0.0,2.394521,0.0,0.0,4.0,0.0,0.0,0.0,4.0,0.0,0.0,140249.565,0.0,0.0,0.0,724806.0,0.0,0.0,0.0,0.0,0.0,0.0,245781.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.339099,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,179055.0,179055.0,179055.0,179055.0,1.000000,1.000000,24.0,24.0,-606.0,0.000000,0.0,0.0,0.0,0.0,0.0,15.000000,0
1,100003,4.790750,0.132217,4.183333,1.145199,45.931507,2.0,135000.0,0.0,3.254795,0.070862,3.249315,0.797260,0,0,NaN,0.311267,0.466757,4,1,1.0,0.000000,0.0,0.0,0,4.0,1.0,3.0,1017400.500,0.0,0.0,0.0,0.0,0.0,0.0,0.25,0.000000,0.000,0.0,3.837671,0.0,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,922500.000,0.0,0.0,0.0,94900.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,0.0,0.0,1.0,0.0,435436.5,900000.0,484191.0,1035882.0,1.057664,0.989013,10.0,12.0,-746.0,0.666667,0.0,0.0,0.0,0.0,0.0,5.785714,0

In [57]:
for cols in master_df.columns:
    print(cols, master_df[cols].isnull().sum(), master_df[cols].dtype)

SK_ID_CURR 0 int64
credit_income_ratio 0 float64
annuity_income_ratio 12 float64
goods_income_ratio 267 float64
credit_goods_ratio 267 float64
age_years 0 float64
count_family_members 0 float64
per_capita_income 0 float64
children_ratio 0 float64
employment_years 0 float64
employment_age_ratio 0 float64
registration_years 0 float64
id_publish_years 0 float64
owns_house 0 int32
owns_car 0 int32
own_car_age 192952 float64
ext_min 104 float64
ext_mean 104 float64
contact_count 0 int64
document_count 0 int64
social_default_cnt 773 float64
social_risk_ratio 773 float64
total_credit_enquiries 0 float64
enquiry_L1M 0 float64
high_credit_hunger_flag 0 int32
total_tradelines 41640 float64
total_active_tradelines 41640 float64
total_closed_tradelines 41640 float64
total_credit_exposure 41640 float64
total_debt 41640 float64
total_overdue 41640 float64
max_overdue 41640 float64
avg_credit_overdue_days 41640 float64
max_credit_overdue_days 41640 float64
credit_prolongation_count 41640 float64
active_pct_tradelines 41640 float64
debt_to_utilization_ratio 41640 float64
avg_debt_per_tradeline 41640 float64
ever_delinquent_flag 41640 float64
avg_credit_age_years 41640 float64
num_accounts_AL 41640 float64
num_accounts_BL 41640 float64
num_accounts_CC 41640 float64
num_accounts_HL 41640 float64
num_accounts_INV 41640 float64
num_accounts_OTH 41640 float64
num_accounts_PL 41640 float64
total_exposure_AL 41640 float64
total_exposure_BL 41640 float64
total_exposure_CC 41640 float64
total_exposure_HL 41640 float64
total_exposure_INV 41640 float64
total_exposure_OTH 41640 float64
total_exposure_PL 41640 float64
total_debt_AL 41640 float64
total_debt_BL 41640 float64
total_debt_CC 41640 float64
total_debt_HL 41640 float64
total_debt_INV 41640 float64
total_debt_OTH 41640 float64
total_debt_PL 41640 float64
total_overdue_AL 41640 float64
total_overdue_BL 41640 float64
total_overdue_CC 41640 float64
total_overdue_HL 41640 float64
total_overdue_INV 41640 float64
total_overdue_OTH 41640 float64
total_overdue_PL 41640 float64
utilization_AL 41640 float64
utilization_BL 41640 float64
utilization_CC 41640 float64
utilization_HL 41640 float64
utilization_INV 41640 float64
utilization_OTH 41640 float64
utilization_PL 41640 float64
active_al 41640 float64
active_bl 41640 float64
active_cc 41640 float64
active_hl 41640 float64
active_inv 41640 float64
active_oth 41640 float64
active_pl 41640 float64
PL_max_dpd_l1m 41640 float64
PL_max_dpd_l3m 41640 float64
PL_max_dpd_l6m 41640 float64
PL_max_dpd_l12m 41640 float64
PL_cnt_30dpd_l1m 41640 float64
PL_cnt_60dpd_l1m 41640 float64
PL_cnt_90dpd_l1m 41640 float64
PL_cnt_30dpd_l3m 41640 float64
PL_cnt_60dpd_l3m 41640 float64
PL_cnt_90dpd_l3m 41640 float64
PL_cnt_30dpd_l6m 41640 float64
PL_cnt_60dpd_l6m 41640 float64
PL_cnt_90dpd_l6m 41640 float64
PL_cnt_30dpd_l12m 41640 float64
PL_cnt_60dpd_l12m 41640 float64
PL_cnt_90dpd_l12m 41640 float64
CC_max_dpd_l1m 41640 float64
CC_max_dpd_l3m 41640 float64
CC_max_dpd_l6m 41640 float64
CC_max_dpd_l12m 41640 float64
CC_cnt_30dpd_l1m 41640 float64
CC_cnt_60dpd_l1m 41640 float64
CC_cnt_90dpd_l1m 41640 float64
CC_cnt_30dpd_l3m 41640 float64
CC_cnt_60dpd_l3m 41640 float64
CC_cnt_90dpd_l3m 41640 float64
CC_cnt_30dpd_l6m 41640 float64
CC_cnt_60dpd_l6m 41640 float64
CC_cnt_90dpd_l6m 41640 float64
CC_cnt_30dpd_l12m 41640 float64
CC_cnt_60dpd_l12m 41640 float64
CC_cnt_90dpd_l12m 41640 float64
HL_max_dpd_l1m 41640 float64
HL_max_dpd_l3m 41640 float64
HL_max_dpd_l6m 41640 float64
HL_max_dpd_l12m 41640 float64
HL_cnt_30dpd_l1m 41640 float64
HL_cnt_60dpd_l1m 41640 float64
HL_cnt_90dpd_l1m 41640 float64
HL_cnt_30dpd_l3m 41640 float64
HL_cnt_60dpd_l3m 41640 float64
HL_cnt_90dpd_l3m 41640 float64
HL_cnt_30dpd_l6m 41640 float64
HL_cnt_60dpd_l6m 41640 float64
HL_cnt_90dpd_l6m 41640 float64
HL_cnt_30dpd_l12m 41640 float64
HL_cnt_60dpd_l12m 41640 float64
HL_cnt_90dpd_l12m 41640 float64
AL_max_dpd_l1m 41640 float64
AL_max_dpd_l3m 41640 float64
AL_max_dpd_l6m 41640 float64
AL_max_dpd_l12m 41640 float64
AL_cnt_30dpd_l1m 41640 float64
AL_cnt_60dpd_l1m 41640 float64
AL_cnt_90dpd_l1m 41640 float64
AL_cnt_30dpd_l3m 41640 float64
AL_cnt_60dpd_l3m 41640 float64
AL_cnt_90dpd_l3m 41640 float64
AL_cnt_30dpd_l6m 41640 float64
AL_cnt_60dpd_l6m 41640 float64
AL_cnt_90dpd_l6m 41640 float64
AL_cnt_30dpd_l12m 41640 float64
AL_cnt_60dpd_l12m 41640 float64
AL_cnt_90dpd_l12m 41640 float64
BL_max_dpd_l1m 41640 float64
BL_max_dpd_l3m 41640 float64
BL_max_dpd_l6m 41640 float64
BL_max_dpd_l12m 41640 float64
BL_cnt_30dpd_l1m 41640 float64
BL_cnt_60dpd_l1m 41640 float64
BL_cnt_90dpd_l1m 41640 float64
BL_cnt_30dpd_l3m 41640 float64
BL_cnt_60dpd_l3m 41640 float64
BL_cnt_90dpd_l3m 41640 float64
BL_cnt_30dpd_l6m 41640 float64
BL_cnt_60dpd_l6m 41640 float64
BL_cnt_90dpd_l6m 41640 float64
BL_cnt_30dpd_l12m 41640 float64
BL_cnt_60dpd_l12m 41640 float64
BL_cnt_90dpd_l12m 41640 float64
OTH_max_dpd_l1m 41640 float64
OTH_max_dpd_l3m 41640 float64
OTH_max_dpd_l6m 41640 float64
OTH_max_dpd_l12m 41640 float64
OTH_cnt_30dpd_l1m 41640 float64
OTH_cnt_60dpd_l1m 41640 float64
OTH_cnt_90dpd_l1m 41640 float64
OTH_cnt_30dpd_l3m 41640 float64
OTH_cnt_60dpd_l3m 41640 float64
OTH_cnt_90dpd_l3m 41640 float64
OTH_cnt_30dpd_l6m 41640 float64
OTH_cnt_60dpd_l6m 41640 float64
OTH_cnt_90dpd_l6m 41640 float64
OTH_cnt_30dpd_l12m 41640 float64
OTH_cnt_60dpd_l12m 41640 float64
OTH_cnt_90dpd_l12m 41640 float64
INV_max_dpd_l1m 41640 float64
INV_max_dpd_l3m 41640 float64
INV_max_dpd_l6m 41640 float64
INV_max_dpd_l12m 41640 float64
INV_cnt_30dpd_l1m 41640 float64
INV_cnt_60dpd_l1m 41640 float64
INV_cnt_90dpd_l1m 41640 float64
INV_cnt_30dpd_l3m 41640 float64
INV_cnt_60dpd_l3m 41640 float64
INV_cnt_90dpd_l3m 41640 float64
INV_cnt_30dpd_l6m 41640 float64
INV_cnt_60dpd_l6m 41640 float64
INV_cnt_90dpd_l6m 41640 float64
INV_cnt_30dpd_l12m 41640 float64
INV_cnt_60dpd_l12m 41640 float64
INV_cnt_90dpd_l12m 41640 float64
max_dpd_l1m 41640 float64
max_dpd_l3m 41640 float64
max_dpd_l6m 41640 float64
max_dpd_l12m 41640 float64
total_30dpd_l1m 41640 float64
total_60dpd_l1m 41640 float64
total_90dpd_l1m 41640 float64
total_30dpd_l3m 41640 float64
total_60dpd_l3m 41640 float64
total_90dpd_l3m 41640 float64
total_30dpd_l6m 41640 float64
total_60dpd_l6m 41640 float64
total_90dpd_l6m 41640 float64
total_30dpd_l12m 41640 float64
total_60dpd_l12m 41640 float64
total_90dpd_l12m 41640 float64
num_prev_apps 1512 float64
num_approved 1512 float64
num_refused 1512 float64
num_cancelled 1512 float64
approval_rate 1512 float64
rejection_rate 1512 float64
avg_application_amt 1512 float64
max_application_amt 1512 float64
avg_credit_amt 1512 float64
max_credit_amt 1512 float64
avg_credit_grant_ratio 1512 float64
min_credit_grant_ratio 1512 float64
avg_prev_term 1512 float64
max_prev_term 1512 float64
days_since_last_application 1512 float64
insurance_rate 1512 float64
on_us_max_dpd 2632 float64
on_us_avg_dpd 2632 float64
on_us_cnt_30dpd 2632 float64
on_us_cnt_60dpd 2632 float64
on_us_cnt_90dpd 2632 float64
avg_instalment_remaining 2632 float64
TARGET 0 int32

In [59]:
master_df['TARGET'].value_counts(normalize=True)

TARGET
0    0.969908
1    0.030092
Name: proportion, dtype: float64

In [60]:
master_df.to_csv("../Dataset/processed/preliminary_dev_sample.csv", index=False)